// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJ9VaIu4fn64R9WQ7lzdMX5o8-PPV-aY',
    appId: '1:271034771393:android:063e664573a8b5ec533140',
    messagingSenderId: '271034771393',
    projectId: 'burj-al-arab-ed7d5',
    databaseURL: 'https://burj-al-arab-ed7d5.firebaseio.com',
    storageBucket: 'burj-al-arab-ed7d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7XRG0uPNGpUd36P5VB98xIz9Jn-2zw8',
    appId: '1:271034771393:ios:0af3a9d0d5779f50533140',
    messagingSenderId: '271034771393',
    projectId: 'burj-al-arab-ed7d5',
    databaseURL: 'https://burj-al-arab-ed7d5.firebaseio.com',
    storageBucket: 'burj-al-arab-ed7d5.appspot.com',
    iosClientId: '271034771393-jn3ihr5ed93bssje84h555mos3p2r80a.apps.googleusercontent.com',
    iosBundleId: 'com.joneyspark.flashchat',
  );
}
